blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://pkg.go.dev/github.com/hmdsefi/gograph
    about: API documentation and examples.
  - name: Report a security vulnerability
    url: https://github.com/hmdsefi/gograph/security/advisories/new
    about: Please report security problems privately.
